### ISSUE TITLE
/f top sort by worth

### ISSUE THREAD

**Issue by Thunter1** [DaPigGuy/PiggyFactions#41] opened 2020-05-13 10:00 UTC
Please make sure your issue complies with these guidelines:
- * [ ] Idea must have not been suggested previously
- * [ ] Be detailed on what you want & make sure the idea is plausible

### Description

add /f top sort by worth that count in claim spawner value so when people put any spawner in claim the value will increase 
### Extra Information

**Comment by Aericio** [comment] 2020-05-13 11:48
Duplicate of #15

**Closed** 2020-05-13 11:48 UTC
Labels: Resolution: Duplicate, Type: Enhancement
