### ISSUE TITLE
Error ender pearl and potions

### ISSUE THREAD

**Issue by Centoller** [DaPigGuy/PiggyFactions#87] opened 2020-09-03 03:12 UTC
Please make sure your issue complies with these guidelines:
- * [x ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ x] Issue must have not been reported previously
- * [ x] Make sure you are on the latest version of PMMP & PiggyFactions
- * [x ] Have a detailed title.

### Issue Description

- Expected result: What were you expecting to happen? 
that works normal

- Actual result: What actually happened?

plugin makes ender pearl and potions stop working

#### Steps to Reproduce the Issue
1. ... play factions, claim among others
2. ...try to use an ender pearl

### OS and Versions

* PocketMine-MP: 3.15.0
* PiggyFactions: the lastest
* Server OS: Linux

### Extra Information

**Comment by Aericio** [comment] 2020-09-05 09:14
Duplicate of #11

**Closed by Aericio** 2020-09-05 09:14 UTC
Labels: Type: Bug
