### ISSUE TITLE
f home crash

### ISSUE THREAD

**Issue by HugoLeBoss91** [DaPigGuy/PiggyFactions#82] opened 2020-08-19 16:43 UTC
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ ] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

Link to crashdump: 

### Extra Information

[16:27:37] (B[Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null" (EXCEPTION) in "src/pocketmine/level/Position" at line 83(B(B
[16:27:37] (B[Server thread/CRITICAL]: #0 src/pocketmine/entity/Entity(1862): pocketmine\level\Position->getLevelNonNull()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #1 src/pocketmine/Player(3918): pocketmine\entity\Entity->teleport(object pocketmine\level\Position, NULL , NULL )(B(B
[16:27:37] (B[Server thread/CRITICAL]: #2 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/commands/subcommands/homes/HomeSubCommand(24): pocketmine\Player->teleport(object pocketmine\level\Position)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #3 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/commands/subcommands/FactionSubCommand(91): DaPigGuy\PiggyFactions\commands\subcommands\homes\HomeSubCommand->onNormalRun(object pocketmine\Player, object DaPigGuy\PiggyFactions\factions\Faction, object DaPigGuy\PiggyFactions\players\FactionsPlayer, string[4] home, array[0])(B(B
[16:27:37] (B[Server thread/CRITICAL]: #4 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/libs/CortexPE/Commando/BaseCommand(124): DaPigGuy\PiggyFactions\commands\subcommands\FactionSubCommand->onRun(object pocketmine\Player, string[4] home, array[0])(B(B
[16:27:37] (B[Server thread/CRITICAL]: #5 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/libs/CortexPE/Commando/BaseCommand(108): DaPigGuy\PiggyFactions\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\Player, string[4] home, array[0])(B(B
[16:27:37] (B[Server thread/CRITICAL]: #6 src/pocketmine/command/SimpleCommandMap(248): DaPigGuy\PiggyFactions\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\Player, string[1] f, array[0])(B(B
[16:27:37] (B[Server thread/CRITICAL]: #7 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] f home)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #8 src/pocketmine/Player(2311): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] f home)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[7] /f home)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #10 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #12 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #14 src/pocketmine/Player(3250): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #15 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #16 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 85.1.25.241 53862, object raklib\protocol\EncapsulatedPacket, integer 0)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #17 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #18 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #19 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #20 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #21 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1597854457.7375)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #22 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #23 src/pocketmine/Server(1588): pocketmine\Server->start()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #24 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)(B(B
[16:27:37] (B[Server thread/CRITICAL]: #25 src/pocketmine/PocketMine(304): pocketmine\server()(B(B
[16:27:37] (B[Server thread/CRITICAL]: #26 (11): require(string[64] phar:///home/container/server.phar/src/pocketmine/PocketMine.php)(B(B
[16:27:37] (B[Server thread/INFO]: [-] Stuf 0(B(B
[16:27:37] (B[Server thread/INFO]: Stuf 0[/85.1.25.241:53862] déconnecté en raison de Internal server error(B(B
[16:27:37] (B[RakLibServer thread/NOTICE]: Blocked 85.1.25.241 for 5 seconds(B(B
[16:27:45] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> ah(B(B
[16:27:48] (B[Server thread/INFO]: Stuf 0[/85.1.25.241:53862] s'est connecté avec l'ID d'entité 963 à (Hub, 259.6342, 78, 219.696)(B(B
[16:27:54] (B[Server thread/INFO]: [+] Stuf 0(B(B
[16:27:59] (B[Server thread/INFO]: [modo-test](B Stuf 0 > oui(B(B
[16:28:20] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> je sais(B(B
[16:28:22] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> 2s(B(B
[16:28:24] (B[Server thread/INFO]: [] TheOnyxbest > il y a un monde ressource ?(B(B
[16:28:45] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> nn(B(B
[16:28:49] (B[Server thread/INFO]: [] TheOnyxbest > ah(B(B
[16:28:51] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> mine il y a des grottes(B(B
[16:28:56] (B[Server thread/INFO]: [Syrie] Hacheroutoto > yo onyx(B(B
[16:28:59] (B[Server thread/INFO]: [HugoLeBoss91: Changez le temps à 1000](B(B
[16:29:01] (B[Server thread/INFO]: [] TheOnyxbest > il y a des ec?(B(B
[16:29:03] (B[Server thread/INFO]: [] TheOnyxbest > cc(B(B
[16:29:04] (B[Server thread/INFO]: [HugoLeBoss91: Stuf 0 a été téléporté à HugoLeBoss91](B(B
[16:29:10] (B[Server thread/INFO]: [Syrie] Hacheroutoto > cv(B(B
[16:29:11] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> stuf(B(B
[16:29:15] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> fais /f home(B(B
[16:29:16] (B[Server thread/INFO]: [] TheOnyxbest > oui et toi(B(B
[16:29:18] (B[Server thread/INFO]: [ONU] Owner HugoLeBoss91 >> ici(B(B
[16:29:27] (B[Server thread/CRITICAL]: pocketmine\utils\AssumptionFailedError: "Position world is null" (EXCEPTION) in "src/pocketmine/level/Position" at line 83(B(B
[16:29:27] (B[Server thread/CRITICAL]: #0 src/pocketmine/entity/Entity(1862): pocketmine\level\Position->getLevelNonNull()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #1 src/pocketmine/Player(3918): pocketmine\entity\Entity->teleport(object pocketmine\level\Position, NULL , NULL )(B(B
[16:29:27] (B[Server thread/CRITICAL]: #2 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/commands/subcommands/homes/HomeSubCommand(24): pocketmine\Player->teleport(object pocketmine\level\Position)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #3 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/commands/subcommands/FactionSubCommand(91): DaPigGuy\PiggyFactions\commands\subcommands\homes\HomeSubCommand->onNormalRun(object pocketmine\Player, object DaPigGuy\PiggyFactions\factions\Faction, object DaPigGuy\PiggyFactions\players\FactionsPlayer, string[4] home, array[0])(B(B
[16:29:27] (B[Server thread/CRITICAL]: #4 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/libs/CortexPE/Commando/BaseCommand(124): DaPigGuy\PiggyFactions\commands\subcommands\FactionSubCommand->onRun(object pocketmine\Player, string[4] home, array[0])(B(B
[16:29:27] (B[Server thread/CRITICAL]: #5 plugins/PiggyFactions_dev-124.phar/src/DaPigGuy/PiggyFactions/libs/CortexPE/Commando/BaseCommand(108): DaPigGuy\PiggyFactions\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\Player, string[4] home, array[0])(B(B
[16:29:27] (B[Server thread/CRITICAL]: #6 src/pocketmine/command/SimpleCommandMap(248): DaPigGuy\PiggyFactions\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\Player, string[1] f, array[0])(B(B
[16:29:27] (B[Server thread/CRITICAL]: #7 src/pocketmine/Server(1811): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] f home)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #8 src/pocketmine/Player(2311): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] f home)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[7] /f home)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #10 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #12 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #14 src/pocketmine/Player(3250): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #15 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #16 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 85.1.25.241 53862, object raklib\protocol\EncapsulatedPacket, integer 0)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #17 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #18 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #19 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #20 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #21 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1597854567.0874)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #22 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #23 src/pocketmine/Server(1588): pocketmine\Server->start()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #24 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)(B(B
[16:29:27] (B[Server thread/CRITICAL]: #25 src/pocketmine/PocketMine(304): pocketmine\server()(B(B
[16:29:27] (B[Server thread/CRITICAL]: #26 (11): require(string[64] phar:///home/container/server.phar/src/pocketmine/PocketMine.php)(B(B

**Comment by Aericio** [comment] 2020-08-19 20:52
Duplicate of #81

**Closed by Aericio** 2020-08-19 20:52 UTC
Labels: Resolution: Duplicate, Type: Bug
