### ISSUE TITLE
Flight configuration in config

### ISSUE THREAD

**Issue by HugoLeBoss91** [DaPigGuy/PiggyFactions#38] opened 2020-05-12 17:37 UTC
Please make sure your issue complies with these guidelines:
- * [x] Idea must have not been suggested previously
- * [x] Be detailed on what you want & make sure the idea is plausible

### Description
Added the possibility to deactivate / f fly in config.yml
### Extra Information

**Comment by Thunder33345** [comment] 2020-05-12 18:19
duplicate of #31

**Comment by Thunder33345** [comment] 2020-05-12 18:19
oops read it wrongly

**Comment by DaPigGuy** [comment] 2020-05-13 00:45
If using PurePerms  or Hierarchy, you can remove the permission for /f fly from players.

**Closed by DaPigGuy** 2020-05-13 00:45 UTC
Labels: Type: Enhancement
