### ISSUE TITLE
Faction home world not loaded 

### ISSUE THREAD

**Issue by Omlo0417** [DaPigGuy/PiggyFactions#81] opened 2020-08-18 01:43 UTC
Please make sure your issue complies with these guidelines:
- * [ ] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [ ] Issue must have not been reported previously
- * [ *] Make sure you are on the latest version of PMMP & PiggyFactions
- * [ ] Have a detailed title.

Link to crashdump: 

### Extra Information

 This error appear when a one player died, cant enter again 
```
[00:56:32] [Server thread/CRITICAL] :

InvalidArgumentException: "Spawn position must

reference a valid and loaded World" (EXCEPTION)

in

"src/pocketmine/event/player/Player Respawn Event" at line 47 [00:56:32] [Server thread/CRITICAL]: #0

plugins/PigeyFactions

(1). phar/src/DaPigGuy/PiggyFactions/EventListener

(148): pocketmine event\player\PlayerRespawnEvent

>set Respawn Position (object pocketmine level Position)

[00:56:32] [Server thread/CRITICAL]: #1

src/pocketmine/plugin/MethodEventExecutor (42): PigGy\Piggy Factions\ Event Listener >onRespawn (object

pocketmine\event\player\PLayer Respawn Event) [00:56:32] [Server thread/CRITICAL]: #2 src/pocketmine/plugin/Registered Listener (80): pocketmine\plugin\Method EventExecutor

>execute(object PigGy\Piggy Factions Event Listener, object

pocketmine \event\player\Player Respawn Event)
```

And This when use /f home

```
[01:09:53] [Server thread/CRITICAL] : pocketmine utils Assumption Failed Error: "Position world is null" (EXCEPTION) in

"src/pocketmine/level/Position" at line 83

[01:09:53] [Server thread/CRITICAL]: #0 src/pocketmine/entity/Entity(1862):

pocketmine\level\Position->getLevel NonNull()

[01:09:53] [Server thread/CRITICAL): #1 src/pocketmine/Player (3918):

pocketmine\entity\Entity->teleport(object

pocketmine\level Position, NULL, NULL)

[01:09:53] [Server thread/CRITICAL]: #2 plugins/PiggyFactions

(1).phar/src/PigGy/Piggy Factions/commands/subc commands/homes/ Home SubCommand (24): pocketmine\Player->teleport(object

pocketmine\level\Position)

[01:09:53] [Server thread/CRITICAL]: # 3 plugins/Piggy Factions

(1).phar/src/PigGy/Piggy Factions/commands/subc ommands/FactionSubCommand (91): PigGy Piggy Factions commands subcommands homes Home SubCommand->on Normal Run(object

pocketmine\Player, object PigGy Piggy Factions\factions\ Faction, object

DaPig Guy\Piggy Factions\players\Factions Player, string[4] home, array[0])

[01:09:53] [Server thread/CRITICAL]: #4 plugins/PiggyFactions

(1). phar/src/PigGy/Piggy Factions/libs/Cortex

/Commando/BaseCommand (124):

PigGy\Piggy Factions commands subcommands Facti onSub Command->to Run(object pocketmine\Player
```

**Comment by Aericio** [comment] 2020-08-18 01:46
Version information needed.

**Comment by Omlo0417** [comment] 2020-08-18 01:52
Sorry, versión [01:51:10] [Server thread/INFO]: This server is running PocketMine-MP 3.15.0 for Minecraft: Bedrock Edition v1.16.20 (protocol version 408)
And Piggy Faction v1. 1.1

**Comment by Aericio** [comment] 2020-09-05 09:24
Duplicate of #72

**Closed by Aericio** 2020-09-05 09:24 UTC
Labels: Type: Bug
